---
name: cmpsc-101-fall-2018-practical7
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalseven/experiment/Experiment.java:
            --multi 2 --language Java
            --fragment "println(" --count 11 --exact
src/main:
    java:
        practicalseven/experiment/RunCampaign.java:
            --multi 4 --language Java
            --fragment "println(" --count 3 --exact
src/main:
    java:
        practicalseven/sort/QuickSort.java:
            --multi 4 --language Java
            --single 4 --language Java
            --fragment "TODO" --count 0 --exact
# --> check the number of commits beyond a threshold
--commits 18
# --> check that the program executes correctly
--command "gradle -q --console plain run" --executes
